# Generated by Django 2.0.1 on 2018-04-26 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='languge',
            new_name='language',
        ),
    ]
